// Questions bank
const allQuestions = {
    'Geography': [
        { q: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2 },
        { q: "Which river is the longest in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1 },
        { q: "Mount Everest is located in which mountain range?", options: ["Alps", "Andes", "Himalayas", "Rockies"], correct: 2 },
        { q: "Which country has the most natural lakes?", options: ["USA", "Russia", "Canada", "Brazil"], correct: 2 },
        { q: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], correct: 1 },
        { q: "Which desert is the largest in the world?", options: ["Sahara", "Gobi", "Antarctic", "Arabian"], correct: 2 },
        { q: "What is the capital of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correct: 2 },
        { q: "Which ocean is the deepest?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correct: 2 },
        { q: "In which country would you find the Great Barrier Reef?", options: ["Indonesia", "Philippines", "Australia", "Thailand"], correct: 2 },
        { q: "What is the largest island in the world?", options: ["Borneo", "Madagascar", "Greenland", "New Guinea"], correct: 2 },
        { q: "What is the capital of Japan?", options: ["Seoul", "Tokyo", "Kyoto", "Osaka"], correct: 1 },
        { q: "Which continent is the Sahara Desert located on?", options: ["Asia", "South America", "Africa", "Australia"], correct: 2 },
        { q: "What is the capital of Canada?", options: ["Toronto", "Ottawa", "Vancouver", "Montreal"], correct: 1 },
        { q: "Which U.S. state is known as the Aloha State?", options: ["California", "Florida", "Hawaii", "Alaska"], correct: 2 },
        { q: "Which country is home to the city of Barcelona?", options: ["Portugal", "Italy", "Spain", "France"], correct: 2 },
        { q: "What is the capital of Egypt?", options: ["Cairo", "Alexandria", "Giza", "Luxor"], correct: 0 },
        { q: "Which mountain range separates Europe and Asia in Russia?", options: ["Andes", "Ural Mountains", "Alps", "Carpathians"], correct: 1 },
        { q: "Which river flows through Paris?", options: ["Danube", "Rhine", "Seine", "Thames"], correct: 2 },
        { q: "What is the capital of Argentina?", options: ["Lima", "Santiago", "Bogota", "Buenos Aires"], correct: 3 },
        { q: "Which country has the city of Marrakech?", options: ["Morocco", "Tunisia", "Jordan", "Algeria"], correct: 0 },
        { q: "What is the largest country in South America by area?", options: ["Argentina", "Brazil", "Peru", "Colombia"], correct: 1 },
        { q: "Which sea lies between Saudi Arabia and Africa?", options: ["Black Sea", "Red Sea", "Arabian Sea", "Caspian Sea"], correct: 1 },
        { q: "What is the capital of Norway?", options: ["Oslo", "Bergen", "Stockholm", "Helsinki"], correct: 0 },
        { q: "Which country is shaped like a boot?", options: ["Greece", "Spain", "Italy", "Croatia"], correct: 2 },
        { q: "What is the capital of Kenya?", options: ["Lagos", "Nairobi", "Kampala", "Addis Ababa"], correct: 1 },
        { q: "Which desert covers much of northern China and southern Mongolia?", options: ["Kalahari", "Gobi", "Atacama", "Namib"], correct: 1 },
        { q: "What is the capital of South Korea?", options: ["Busan", "Seoul", "Incheon", "Daegu"], correct: 1 },
        { q: "Which country had the largest population in the world as of 2026?", options: ["China", "India", "United States", "Indonesia"], correct: 1 },
        { q: "What is the capital of New Zealand?", options: ["Auckland", "Christchurch", "Wellington", "Hamilton"], correct: 2 },
        { q: "Which river runs through Egypt?", options: ["Tigris", "Jordan", "Nile", "Congo"], correct: 2 },
        { q: "Which country borders both Spain and Germany?", options: ["Belgium", "France", "Switzerland", "Austria"], correct: 1 },
        { q: "What is the capital of Turkey?", options: ["Istanbul", "Ankara", "Izmir", "Antalya"], correct: 1 },
        { q: "Which U.S. state is the Grand Canyon located in?", options: ["Utah", "Nevada", "Arizona", "Colorado"], correct: 2 },
        { q: "What is the capital of Thailand?", options: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"], correct: 0 },
        { q: "Which African country has Cape Town as one of its capitals?", options: ["South Africa", "Namibia", "Botswana", "Zimbabwe"], correct: 0 },
        { q: "What is the capital of Peru?", options: ["Cusco", "Lima", "Quito", "La Paz"], correct: 1 },
        { q: "Which ocean lies on the east coast of the United States?", options: ["Pacific", "Indian", "Arctic", "Atlantic"], correct: 3 },
        { q: "Which country contains the ancient city of Petra?", options: ["Jordan", "Lebanon", "Israel", "Syria"], correct: 0 },
        { q: "What is the capital of Sweden?", options: ["Stockholm", "Gothenburg", "Malmo", "Uppsala"], correct: 0 },
        { q: "Which country is directly south of the United States?", options: ["Guatemala", "Cuba", "Mexico", "Belize"], correct: 2 },
        { q: "What is the capital of Vietnam?", options: ["Ho Chi Minh City", "Da Nang", "Hue", "Hanoi"], correct: 3 },
        { q: "Which country has the longest coastline in the world?", options: ["Russia", "Australia", "Canada", "Indonesia"], correct: 2 },
        { q: "What is the capital of the Netherlands?", options: ["Rotterdam", "Amsterdam", "The Hague", "Utrecht"], correct: 1 },
        { q: "Which river flows through Budapest?", options: ["Danube", "Volga", "Elbe", "Po"], correct: 0 },
        { q: "What is the capital of Chile?", options: ["Santiago", "Valparaiso", "Lima", "Bogota"], correct: 0 },
        { q: "Which country is known as the Land of a Thousand Lakes?", options: ["Norway", "Sweden", "Finland", "Iceland"], correct: 2 },
        { q: "What is the capital of Portugal?", options: ["Porto", "Lisbon", "Madrid", "Braga"], correct: 1 },
        { q: "Which U.S. state is Mount Rushmore located in?", options: ["Wyoming", "South Dakota", "Montana", "North Dakota"], correct: 1 },
        { q: "What is the capital of Colombia?", options: ["Bogota", "Medellin", "Cartagena", "Quito"], correct: 0 },
        { q: "Which country has the city of Dubrovnik?", options: ["Croatia", "Slovenia", "Serbia", "Montenegro"], correct: 0 },
        { q: "What is the capital of Austria?", options: ["Vienna", "Salzburg", "Graz", "Innsbruck"], correct: 0 },
        { q: "Which two continents does the Equator cross?", options: ["Europe and Asia", "Africa and South America", "North America and Asia", "Australia and Antarctica"], correct: 1 },
        { q: "What is the capital of Switzerland?", options: ["Zurich", "Geneva", "Bern", "Basel"], correct: 2 },
        { q: "Which country is famous for its fjords?", options: ["Denmark", "Norway", "Estonia", "Latvia"], correct: 1 },
        { q: "What is the capital of Poland?", options: ["Krakow", "Warsaw", "Gdansk", "Wroclaw"], correct: 1 },
        { q: "Which country is home to Mount Kilimanjaro?", options: ["Kenya", "Uganda", "Tanzania", "Ethiopia"], correct: 2 },
        { q: "What is the capital of Greece?", options: ["Athens", "Thessaloniki", "Sparta", "Patras"], correct: 0 },
        { q: "Which river carved the Grand Canyon?", options: ["Colorado River", "Missouri River", "Rio Grande", "Columbia River"], correct: 0 },
        { q: "What is the capital of Hungary?", options: ["Budapest", "Bucharest", "Belgrade", "Bratislava"], correct: 0 },
        { q: "Which country includes the island of Sicily?", options: ["Greece", "Italy", "Spain", "Malta"], correct: 1 },
        { q: "What is the capital of Denmark?", options: ["Copenhagen", "Aarhus", "Odense", "Malmo"], correct: 0 },
        { q: "Which country has the city of Casablanca?", options: ["Morocco", "Egypt", "Algeria", "Tunisia"], correct: 0 },
        { q: "What is the capital of Ireland?", options: ["Dublin", "Cork", "Galway", "Limerick"], correct: 0 },
        { q: "Which major desert is in northern Africa?", options: ["Patagonian", "Sahara", "Sonoran", "Taklamakan"], correct: 1 },
        { q: "What is the capital of Belgium?", options: ["Brussels", "Antwerp", "Bruges", "Ghent"], correct: 0 },
        { q: "Which country has the city of Krakow?", options: ["Poland", "Czech Republic", "Slovakia", "Lithuania"], correct: 0 },
        { q: "What is the capital of Finland?", options: ["Oslo", "Helsinki", "Stockholm", "Turku"], correct: 1 },
        { q: "Which country contains most of the Amazon rainforest?", options: ["Peru", "Brazil", "Ecuador", "Bolivia"], correct: 1 },
        { q: "What is the capital of the Czech Republic?", options: ["Prague", "Brno", "Bratislava", "Plzen"], correct: 0 },
        { q: "Which country has the islands of Zanzibar?", options: ["Kenya", "Mozambique", "Tanzania", "Madagascar"], correct: 2 },
        { q: "What is the capital of Romania?", options: ["Budapest", "Bucharest", "Sofia", "Belgrade"], correct: 1 },
        { q: "Which country lies immediately north of the United States?", options: ["Canada", "Mexico", "Russia", "Greenland"], correct: 0 },
        { q: "What is the capital of Saudi Arabia?", options: ["Jeddah", "Mecca", "Riyadh", "Doha"], correct: 2 },
        { q: "Which country has the city of Medellin?", options: ["Colombia", "Venezuela", "Chile", "Ecuador"], correct: 0 },
        { q: "What is the capital of Indonesia?", options: ["Jakarta", "Bali", "Surabaya", "Bandung"], correct: 0 },
        { q: "Which country contains the region of Transylvania?", options: ["Romania", "Hungary", "Bulgaria", "Ukraine"], correct: 0 },
        { q: "What is the capital of Malaysia?", options: ["Kuala Lumpur", "George Town", "Johor Bahru", "Malacca City"], correct: 0 },
        { q: "Which country has the city of Kyoto?", options: ["China", "South Korea", "Japan", "Thailand"], correct: 2 },
        { q: "What is the capital of Iceland?", options: ["Reykjavik", "Akureyri", "Oslo", "Bergen"], correct: 0 },
        { q: "Which country has the city of Lahore?", options: ["India", "Pakistan", "Bangladesh", "Nepal"], correct: 1 },
        { q: "What is the capital of Pakistan?", options: ["Karachi", "Lahore", "Islamabad", "Rawalpindi"], correct: 2 },
        { q: "Which country has the city of Nice?", options: ["Italy", "Spain", "France", "Belgium"], correct: 2 },
        { q: "What is the capital of Cuba?", options: ["Santiago de Cuba", "Havana", "Kingston", "San Juan"], correct: 1 },
        { q: "Which country has the city of Naples?", options: ["Italy", "Greece", "Croatia", "France"], correct: 0 },
        { q: "What is the capital of Ukraine?", options: ["Kyiv", "Lviv", "Odesa", "Kharkiv"], correct: 0 },
        { q: "Which country has the city of Quito?", options: ["Peru", "Colombia", "Ecuador", "Bolivia"], correct: 2 },
        { q: "What is the capital of Venezuela?", options: ["Caracas", "Maracaibo", "Valencia", "Bogota"], correct: 0 },
        { q: "Which country has the city of Salzburg?", options: ["Austria", "Germany", "Switzerland", "Poland"], correct: 0 },
        { q: "What is the capital of Ethiopia?", options: ["Addis Ababa", "Nairobi", "Asmara", "Kigali"], correct: 0 },
        { q: "Which country has the city of Porto?", options: ["Spain", "Portugal", "Italy", "France"], correct: 1 },
        { q: "What is the capital of Bangladesh?", options: ["Dhaka", "Chittagong", "Kathmandu", "Colombo"], correct: 0 },
        { q: "Which country has the city of Jaipur?", options: ["India", "Nepal", "Sri Lanka", "Pakistan"], correct: 0 },
        { q: "What is the capital of Nigeria?", options: ["Lagos", "Abuja", "Kano", "Accra"], correct: 1 },
        { q: "Which country has the city of Bruges?", options: ["Netherlands", "Belgium", "France", "Luxembourg"], correct: 1 },
        { q: "What is the capital of Nepal?", options: ["Kathmandu", "Thimphu", "Dhaka", "Delhi"], correct: 0 },
        { q: "Which country has the city of Split?", options: ["Croatia", "Serbia", "Bosnia and Herzegovina", "Slovenia"], correct: 0 },
        { q: "What is the constitutional capital of Bolivia?", options: ["La Paz", "Santa Cruz", "Sucre", "Cochabamba"], correct: 2 },
        { q: "Which country has the city of Pune?", options: ["Pakistan", "India", "Nepal", "Bangladesh"], correct: 1 },
        { q: "What is the capital of Morocco?", options: ["Casablanca", "Rabat", "Marrakech", "Fes"], correct: 1 },
        { q: "Which country has the city of Recife?", options: ["Portugal", "Argentina", "Brazil", "Chile"], correct: 2 },
        { q: "What is the capital of Algeria?", options: ["Oran", "Algiers", "Tunis", "Tripoli"], correct: 1 },
        { q: "Which country has the city of Valencia?", options: ["Portugal", "Spain", "Italy", "Mexico"], correct: 1 },
        { q: "What is the capital of Croatia?", options: ["Zagreb", "Split", "Dubrovnik", "Ljubljana"], correct: 0 },
        { q: "Which country has the city of Cusco?", options: ["Peru", "Bolivia", "Chile", "Ecuador"], correct: 0 },
        { q: "What is the capital of Bulgaria?", options: ["Sofia", "Bucharest", "Skopje", "Belgrade"], correct: 0 },
        { q: "Which country has the city of Busan?", options: ["Japan", "South Korea", "China", "Vietnam"], correct: 1 },
        { q: "What is the capital of Serbia?", options: ["Sarajevo", "Belgrade", "Sofia", "Skopje"], correct: 1 },
        { q: "Which river flows through London?", options: ["Seine", "Thames", "Rhine", "Danube"], correct: 1 },
        { q: "What is the capital of Slovenia?", options: ["Ljubljana", "Zagreb", "Bratislava", "Skopje"], correct: 0 },
        { q: "Which country has the city of Fez?", options: ["Morocco", "Tunisia", "Libya", "Egypt"], correct: 0 },
        { q: "What is the capital of Slovakia?", options: ["Prague", "Bratislava", "Budapest", "Ljubljana"], correct: 1 },
        { q: "Which country has the city of Osaka?", options: ["China", "Japan", "South Korea", "Taiwan"], correct: 1 },
        { q: "What is the capital of Tunisia?", options: ["Tunis", "Sfax", "Rabat", "Tripoli"], correct: 0 }
    ],
    'Entertainment': [
        { q: "Who directed 'Jurassic Park'?", options: ["James Cameron", "Steven Spielberg", "George Lucas", "Ridley Scott"], correct: 1 },
        { q: "Which band performed 'Bohemian Rhapsody'?", options: ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"], correct: 2 },
        { q: "What year was the first Harry Potter movie released?", options: ["1999", "2000", "2001", "2002"], correct: 2 },
        { q: "Who played Jack in 'Titanic'?", options: ["Brad Pitt", "Leonardo DiCaprio", "Tom Cruise", "Johnny Depp"], correct: 1 },
        { q: "Which TV show features a character named Walter White?", options: ["The Wire", "Breaking Bad", "Better Call Saul", "Ozark"], correct: 1 },
        { q: "What is the name of Batman's butler?", options: ["Alfred", "Jarvis", "Geoffrey", "Winston"], correct: 0 },
        { q: "Which artist sang 'Thriller'?", options: ["Prince", "Michael Jackson", "Whitney Houston", "Stevie Wonder"], correct: 1 },
        { q: "In 'The Lion King', what is Simba's father's name?", options: ["Scar", "Mufasa", "Rafiki", "Zazu"], correct: 1 },
        { q: "Which movie won Best Picture at the 2020 Oscars?", options: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"], correct: 2 },
        { q: "What instrument does Sherlock Holmes play?", options: ["Piano", "Violin", "Cello", "Flute"], correct: 1 },
        { q: "Who directed 'E.T. the Extra-Terrestrial'?", options: ["George Lucas", "Steven Spielberg", "Tim Burton", "Ron Howard"], correct: 1 },
        { q: "Which singer is known as the Material Girl?", options: ["Madonna", "Cyndi Lauper", "Cher", "Lady Gaga"], correct: 0 },
        { q: "What is the name of the coffee shop in 'Friends'?", options: ["Central Cafe", "Coffee House", "Central Perk", "Daily Grind"], correct: 2 },
        { q: "Who played Hermione Granger in the Harry Potter films?", options: ["Emma Watson", "Keira Knightley", "Saoirse Ronan", "Millie Bobby Brown"], correct: 0 },
        { q: "Which band released the album 'Abbey Road'?", options: ["The Rolling Stones", "Queen", "The Beatles", "The Who"], correct: 2 },
        { q: "What is the highest-grossing film of James Cameron's early blockbuster era about a ship?", options: ["Avatar", "Titanic", "Aliens", "The Abyss"], correct: 1 },
        { q: "Which actor played Iron Man in the Marvel Cinematic Universe?", options: ["Chris Evans", "Robert Downey Jr.", "Mark Ruffalo", "Chris Hemsworth"], correct: 1 },
        { q: "What is the fictional African nation in 'Black Panther'?", options: ["Zamunda", "Wakanda", "Genosha", "Latveria"], correct: 1 },
        { q: "Which singer performed 'Rolling in the Deep'?", options: ["Adele", "Beyonce", "Amy Winehouse", "Dua Lipa"], correct: 0 },
        { q: "Who created the TV series 'The Simpsons'?", options: ["Seth MacFarlane", "Matt Groening", "Mike Judge", "Dan Harmon"], correct: 1 },
        { q: "Which movie features the quote 'I'll be back'?", options: ["Predator", "RoboCop", "Die Hard", "The Terminator"], correct: 3 },
        { q: "What is the name of the snowman in Disney's 'Frozen'?", options: ["Olaf", "Sven", "Kristoff", "Hans"], correct: 0 },
        { q: "Which band was Freddie Mercury the lead singer of?", options: ["The Doors", "Queen", "ABBA", "ELO"], correct: 1 },
        { q: "Who directed 'Pulp Fiction'?", options: ["Martin Scorsese", "Guy Ritchie", "Quentin Tarantino", "David Fincher"], correct: 2 },
        { q: "What is the title of the first 'Star Wars' film released in 1977?", options: ["The Empire Strikes Back", "A New Hope", "Return of the Jedi", "The Phantom Menace"], correct: 1 },
        { q: "Which actress played Katniss Everdeen?", options: ["Emma Stone", "Shailene Woodley", "Jennifer Lawrence", "Kristen Stewart"], correct: 2 },
        { q: "Which TV show is set in the fictional land of Westeros?", options: ["The Witcher", "Vikings", "Game of Thrones", "House of the Dragon"], correct: 2 },
        { q: "Who sang 'Like a Prayer'?", options: ["Whitney Houston", "Madonna", "Janet Jackson", "Paula Abdul"], correct: 1 },
        { q: "Which actor voiced Woody in 'Toy Story'?", options: ["Tim Allen", "Tom Hanks", "Billy Crystal", "Robin Williams"], correct: 1 },
        { q: "What is the name of the clownfish in 'Finding Nemo'?", options: ["Marlin", "Dory", "Nemo", "Gill"], correct: 2 },
        { q: "Which artist released the album '1989'?", options: ["Taylor Swift", "Katy Perry", "Lorde", "Selena Gomez"], correct: 0 },
        { q: "Who played the Joker in 'The Dark Knight'?", options: ["Joaquin Phoenix", "Jared Leto", "Heath Ledger", "Jack Nicholson"], correct: 2 },
        { q: "Which musical features the song 'Defying Gravity'?", options: ["Cats", "Les Miserables", "Wicked", "Hamilton"], correct: 2 },
        { q: "What is the name of the school in the Harry Potter series?", options: ["Beauxbatons", "Durmstrang", "Hogwarts", "Ilvermorny"], correct: 2 },
        { q: "Which singer is famous for the hit 'Purple Rain'?", options: ["Prince", "David Bowie", "George Michael", "Elton John"], correct: 0 },
        { q: "Who directed 'The Lord of the Rings' trilogy?", options: ["Peter Jackson", "Ridley Scott", "James Cameron", "Guillermo del Toro"], correct: 0 },
        { q: "Which actor played Captain Jack Sparrow?", options: ["Orlando Bloom", "Jude Law", "Johnny Depp", "Geoffrey Rush"], correct: 2 },
        { q: "Which TV sitcom follows the Bluth family?", options: ["Modern Family", "Arrested Development", "The Office", "Parks and Recreation"], correct: 1 },
        { q: "What is the stage name of Stefani Germanotta?", options: ["Pink", "Kesha", "Lady Gaga", "Sia"], correct: 2 },
        { q: "Which film features a shark terrorizing Amity Island?", options: ["Deep Blue Sea", "Jaws", "Open Water", "The Meg"], correct: 1 },
        { q: "Who played Forrest Gump?", options: ["Tom Cruise", "Tom Hanks", "Kevin Costner", "Robin Williams"], correct: 1 },
        { q: "Which group sang 'Dancing Queen'?", options: ["ABBA", "Ace of Base", "Bananarama", "The Cardigans"], correct: 0 },
        { q: "What is the name of the kingdom in Disney's 'Tangled'?", options: ["Arendelle", "Corona", "Atlantica", "Auradon"], correct: 1 },
        { q: "Which actor starred as Neo in 'The Matrix'?", options: ["Keanu Reeves", "Brad Pitt", "Matt Damon", "Nicolas Cage"], correct: 0 },
        { q: "Who created 'Star Trek'?", options: ["George Lucas", "Gene Roddenberry", "Joss Whedon", "J.J. Abrams"], correct: 1 },
        { q: "Which singer had a hit with 'Umbrella'?", options: ["Beyonce", "Rihanna", "Alicia Keys", "Ciara"], correct: 1 },
        { q: "Which movie is about a theme park with cloned dinosaurs?", options: ["King Kong", "Jurassic Park", "Godzilla", "Congo"], correct: 1 },
        { q: "Who played Wednesday Addams in the 2022 series 'Wednesday'?", options: ["Jenna Ortega", "Emma Myers", "Millie Bobby Brown", "Hailee Steinfeld"], correct: 0 },
        { q: "Which band recorded 'Hotel California'?", options: ["Fleetwood Mac", "The Eagles", "Journey", "Chicago"], correct: 1 },
        { q: "What is the name of the paper company in 'The Office'?", options: ["Sabre", "Dunder Mifflin", "Wernham Hogg", "Staples"], correct: 1 },
        { q: "Which actress played Elle Woods in 'Legally Blonde'?", options: ["Cameron Diaz", "Reese Witherspoon", "Sandra Bullock", "Jennifer Aniston"], correct: 1 },
        { q: "Who sang 'Billie Jean'?", options: ["Prince", "Michael Jackson", "Lionel Richie", "Stevie Wonder"], correct: 1 },
        { q: "Which movie won Best Animated Feature at the first Oscars to award that category?", options: ["Shrek", "Monsters, Inc.", "Ice Age", "Spirited Away"], correct: 0 },
        { q: "What instrument is Elton John most associated with?", options: ["Guitar", "Piano", "Drums", "Saxophone"], correct: 1 },
        { q: "Who played Black Widow in the Marvel films?", options: ["Scarlett Johansson", "Natalie Portman", "Emily Blunt", "Charlize Theron"], correct: 0 },
        { q: "Which TV series features a chemistry teacher turned meth producer?", options: ["Ozark", "Narcos", "Breaking Bad", "Better Call Saul"], correct: 2 },
        { q: "Which artist released 'Born to Run'?", options: ["Bruce Springsteen", "Bob Seger", "Billy Joel", "Tom Petty"], correct: 0 },
        { q: "Who directed 'Inception'?", options: ["Christopher Nolan", "Denis Villeneuve", "David Fincher", "Zack Snyder"], correct: 0 },
        { q: "Which actress voiced Elsa in Disney's 'Frozen'?", options: ["Idina Menzel", "Kristen Bell", "Mandy Moore", "Amy Adams"], correct: 0 },
        { q: "What is the name of Han Solo's ship?", options: ["Star Destroyer", "Serenity", "Millennium Falcon", "Razor Crest"], correct: 2 },
        { q: "Which singer is known for the song 'Shake It Off'?", options: ["Taylor Swift", "Kesha", "Kelly Clarkson", "Miley Cyrus"], correct: 0 },
        { q: "Who played Indiana Jones?", options: ["Harrison Ford", "Mel Gibson", "Kurt Russell", "Alec Baldwin"], correct: 0 },
        { q: "Which show features the character Eleven?", options: ["The Umbrella Academy", "Stranger Things", "Dark", "The OA"], correct: 1 },
        { q: "Which pop star starred in the film 'A Star Is Born' with Bradley Cooper?", options: ["Lady Gaga", "Pink", "Adele", "Katy Perry"], correct: 0 },
        { q: "Which studio created Mickey Mouse?", options: ["Warner Bros.", "Pixar", "Disney", "DreamWorks"], correct: 2 },
        { q: "Who sang 'Respect'?", options: ["Aretha Franklin", "Tina Turner", "Whitney Houston", "Diana Ross"], correct: 0 },
        { q: "Which movie is set in the fictional African kingdom of Zamunda?", options: ["Black Panther", "Coming to America", "The Lion King", "Aladdin"], correct: 1 },
        { q: "Who played Rachel Green on 'Friends'?", options: ["Courteney Cox", "Jennifer Aniston", "Lisa Kudrow", "Julia Roberts"], correct: 1 },
        { q: "Which band released 'Smells Like Teen Spirit'?", options: ["Pearl Jam", "Nirvana", "Soundgarden", "Green Day"], correct: 1 },
        { q: "What is the subtitle of the second 'Lord of the Rings' movie?", options: ["The Return of the King", "The Desolation of Smaug", "The Two Towers", "An Unexpected Journey"], correct: 2 },
        { q: "Which actor played Deadpool?", options: ["Ryan Reynolds", "Chris Pratt", "Paul Rudd", "Jason Bateman"], correct: 0 },
        { q: "Which singer released the album 'Future Nostalgia'?", options: ["Dua Lipa", "Billie Eilish", "Ariana Grande", "Olivia Rodrigo"], correct: 0 },
        { q: "Who directed 'The Grand Budapest Hotel'?", options: ["Noah Baumbach", "Wes Anderson", "Taika Waititi", "Greta Gerwig"], correct: 1 },
        { q: "What is the name of the town in 'Gilmore Girls'?", options: ["Tree Hill", "Stars Hollow", "Sunnydale", "Mystic Falls"], correct: 1 },
        { q: "Which artist sang 'Someone Like You'?", options: ["Adele", "Sam Smith", "Sia", "Ellie Goulding"], correct: 0 },
        { q: "Who played Wonder Woman in the DC films of the 2010s?", options: ["Gal Gadot", "Brie Larson", "Elizabeth Olsen", "Margot Robbie"], correct: 0 },
        { q: "Which film features the characters Buzz Lightyear and Woody?", options: ["A Bug's Life", "Toy Story", "Cars", "Up"], correct: 1 },
        { q: "Which TV series features the Roy family fighting for a media empire?", options: ["Billions", "Mad Men", "Succession", "Empire"], correct: 2 },
        { q: "Who sang 'Jolene'?", options: ["Dolly Parton", "Shania Twain", "Faith Hill", "Linda Ronstadt"], correct: 0 },
        { q: "What is the name of the hotel in 'The Shining'?", options: ["Bates Motel", "Overlook Hotel", "Grand Budapest", "Hotel Cortez"], correct: 1 },
        { q: "Which actress starred as Barbie in the 2023 film 'Barbie'?", options: ["Emma Stone", "Margot Robbie", "Anya Taylor-Joy", "Saoirse Ronan"], correct: 1 },
        { q: "Which band member wrote many songs for Fleetwood Mac and sang 'Edge of Seventeen' solo?", options: ["Christine McVie", "Stevie Nicks", "Lindsey Buckingham", "Mick Fleetwood"], correct: 1 },
        { q: "Who created the sitcom 'Seinfeld' with Jerry Seinfeld?", options: ["Larry David", "Lorne Michaels", "Chuck Lorre", "Greg Daniels"], correct: 0 },
        { q: "Which movie follows a boxer named Rocky Balboa?", options: ["Raging Bull", "Million Dollar Baby", "Rocky", "Creed"], correct: 2 },
        { q: "Which singer's real first name is Robyn?", options: ["Rihanna", "Lorde", "Sia", "Kesha"], correct: 0 },
        { q: "Who played Jack Dawson in 'Titanic'?", options: ["Matt Damon", "Brad Pitt", "Leonardo DiCaprio", "Jude Law"], correct: 2 },
        { q: "Which TV show features Leslie Knope?", options: ["30 Rock", "Veep", "Parks and Recreation", "Brooklyn Nine-Nine"], correct: 2 },
        { q: "Which artist released 'Goodbye Yellow Brick Road'?", options: ["David Bowie", "Billy Joel", "Elton John", "Paul McCartney"], correct: 2 },
        { q: "Who directed 'Get Out'?", options: ["Jordan Peele", "Spike Lee", "Ryan Coogler", "John Singleton"], correct: 0 },
        { q: "Which actor played The Dude in 'The Big Lebowski'?", options: ["Jeff Bridges", "John Goodman", "Steve Buscemi", "Jeff Daniels"], correct: 0 },
        { q: "Which girl group sang 'Wannabe'?", options: ["Destiny's Child", "TLC", "The Spice Girls", "The Pussycat Dolls"], correct: 2 },
        { q: "What is the name of the fictional newspaper in 'Spider-Man'?", options: ["Daily Planet", "Daily Bugle", "New York Bulletin", "The Chronicle"], correct: 1 },
        { q: "Which actress played Princess Leia in the original 'Star Wars' trilogy?", options: ["Carrie Fisher", "Sigourney Weaver", "Linda Hamilton", "Jodie Foster"], correct: 0 },
        { q: "Which singer performed 'Flowers'?", options: ["Selena Gomez", "Miley Cyrus", "Demi Lovato", "Camila Cabello"], correct: 1 },
        { q: "Which film features the quote 'Why so serious?'", options: ["Joker", "The Dark Knight", "Batman Begins", "Suicide Squad"], correct: 1 },
        { q: "Who voiced Donkey in 'Shrek'?", options: ["Chris Rock", "Eddie Murphy", "Martin Lawrence", "Kevin Hart"], correct: 1 },
        { q: "Which TV series follows a soccer coach named Ted Lasso?", options: ["Shrinking", "Trying", "Ted Lasso", "The Morning Show"], correct: 2 },
        { q: "Which artist released the album 'Lemonade'?", options: ["Beyonce", "Rihanna", "SZA", "Alicia Keys"], correct: 0 },
        { q: "Who directed 'Spirited Away'?", options: ["Makoto Shinkai", "Hayao Miyazaki", "Mamoru Hosoda", "Satoshi Kon"], correct: 1 },
        { q: "What is the name of the dragon in 'The Hobbit'?", options: ["Drogon", "Smaug", "Falkor", "Toothless"], correct: 1 },
        { q: "Which actress played Wednesday Addams in the 1991 film 'The Addams Family'?", options: ["Christina Ricci", "Anjelica Huston", "Winona Ryder", "Fairuza Balk"], correct: 0 },
        { q: "Which rock band released 'Back in Black'?", options: ["Metallica", "AC/DC", "Guns N' Roses", "Aerosmith"], correct: 1 },
        { q: "Which movie musical features the characters Danny and Sandy?", options: ["Grease", "Hairspray", "Mamma Mia!", "Chicago"], correct: 0 },
        { q: "Who played the title role in 'Edward Scissorhands'?", options: ["Johnny Depp", "Tom Cruise", "Nicolas Cage", "Brad Pitt"], correct: 0 },
        { q: "Which TV series is set at McKinley High and centers on a glee club?", options: ["Fame", "Smash", "Glee", "Victorious"], correct: 2 },
        { q: "Which singer released 'drivers license'?", options: ["Olivia Rodrigo", "Billie Eilish", "Tate McRae", "Sabrina Carpenter"], correct: 0 },
        { q: "Who directed 'The Shape of Water'?", options: ["Alfonso Cuaron", "Guillermo del Toro", "Alejandro G. Inarritu", "Pedro Almodovar"], correct: 1 },
        { q: "Which actor played Maverick in 'Top Gun'?", options: ["Val Kilmer", "Tom Cruise", "Patrick Swayze", "Kurt Russell"], correct: 1 },
        { q: "Which band released 'Wonderwall'?", options: ["Blur", "Radiohead", "Oasis", "Coldplay"], correct: 2 },
        { q: "What is the name of the virtual world in 'Ready Player One'?", options: ["The Grid", "OASIS", "Metropolis", "Arcadia"], correct: 1 }
    ],
    'History': [
        { q: "In what year did World War II end?", options: ["1943", "1944", "1945", "1946"], correct: 2 },
        { q: "Who was the first President of the United States?", options: ["John Adams", "Thomas Jefferson", "George Washington", "Benjamin Franklin"], correct: 2 },
        { q: "The Great Wall of China was primarily built to defend against which group?", options: ["Japanese", "Mongols", "Koreans", "Vietnamese"], correct: 1 },
        { q: "In which year did the Titanic sink?", options: ["1910", "1912", "1914", "1916"], correct: 1 },
        { q: "Who was the Egyptian queen famous for her beauty?", options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"], correct: 1 },
        { q: "The French Revolution began in which year?", options: ["1776", "1789", "1799", "1804"], correct: 1 },
        { q: "Who discovered America in 1492?", options: ["Amerigo Vespucci", "Christopher Columbus", "Leif Erikson", "Ferdinand Magellan"], correct: 1 },
        { q: "The Renaissance began in which country?", options: ["France", "Spain", "Italy", "England"], correct: 2 },
        { q: "Who was the first man to walk on the moon?", options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Yuri Gagarin"], correct: 1 },
        { q: "The Berlin Wall fell in which year?", options: ["1987", "1988", "1989", "1990"], correct: 2 },
        { q: "Who was the first emperor of Rome?", options: ["Julius Caesar", "Augustus", "Nero", "Trajan"], correct: 1 },
        { q: "In which year did the United States declare independence?", options: ["1775", "1776", "1781", "1789"], correct: 1 },
        { q: "Which ship carried the Pilgrims to North America in 1620?", options: ["Santa Maria", "Mayflower", "Beagle", "Endeavour"], correct: 1 },
        { q: "Who was the British prime minister for most of World War II?", options: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Margaret Thatcher"], correct: 1 },
        { q: "Which ancient civilization built Machu Picchu?", options: ["Maya", "Aztec", "Inca", "Olmec"], correct: 2 },
        { q: "In which year did the American Civil War begin?", options: ["1859", "1861", "1863", "1865"], correct: 1 },
        { q: "Who was known as the Maid of Orleans?", options: ["Marie Antoinette", "Catherine de Medici", "Joan of Arc", "Eleanor of Aquitaine"], correct: 2 },
        { q: "Which city was buried by the eruption of Mount Vesuvius in AD 79?", options: ["Athens", "Pompeii", "Carthage", "Alexandria"], correct: 1 },
        { q: "Who was the first woman to fly solo across the Atlantic Ocean?", options: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Sally Ride"], correct: 0 },
        { q: "Which war was fought between the North and South regions of the United States?", options: ["Revolutionary War", "Civil War", "War of 1812", "Spanish-American War"], correct: 1 },
        { q: "Who was the leader of the Soviet Union during most of World War II?", options: ["Vladimir Lenin", "Joseph Stalin", "Nikita Khrushchev", "Leon Trotsky"], correct: 1 },
        { q: "The Magna Carta was signed in which year?", options: ["1066", "1215", "1415", "1492"], correct: 1 },
        { q: "Which explorer completed the first circumnavigation of the globe expedition?", options: ["Christopher Columbus", "Ferdinand Magellan", "Marco Polo", "Vasco da Gama"], correct: 1 },
        { q: "Who was assassinated on the Ides of March?", options: ["Augustus", "Julius Caesar", "Cicero", "Mark Antony"], correct: 1 },
        { q: "Which empire was ruled by Suleiman the Magnificent?", options: ["Roman Empire", "Ottoman Empire", "Mongol Empire", "Byzantine Empire"], correct: 1 },
        { q: "In which year did the Russian Revolution begin?", options: ["1905", "1914", "1917", "1922"], correct: 2 },
        { q: "Who discovered penicillin in 1928?", options: ["Louis Pasteur", "Alexander Fleming", "Jonas Salk", "Gregor Mendel"], correct: 1 },
        { q: "Which queen ruled Britain during the Victorian era?", options: ["Queen Anne", "Queen Victoria", "Queen Elizabeth I", "Queen Mary"], correct: 1 },
        { q: "What wall was torn down in Germany in 1989?", options: ["Hadrian's Wall", "Berlin Wall", "Great Wall", "Iron Curtain"], correct: 1 },
        { q: "Who was the first President of South Africa elected after apartheid?", options: ["F.W. de Klerk", "Nelson Mandela", "Thabo Mbeki", "Desmond Tutu"], correct: 1 },
        { q: "Which ancient city is associated with the hanging gardens, one of the Seven Wonders?", options: ["Babylon", "Athens", "Memphis", "Tyre"], correct: 0 },
        { q: "Who led the Indian independence movement using nonviolent resistance?", options: ["Jawaharlal Nehru", "Subhas Chandra Bose", "Mahatma Gandhi", "Muhammad Ali Jinnah"], correct: 2 },
        { q: "The attack on Pearl Harbor occurred in which year?", options: ["1939", "1941", "1944", "1945"], correct: 1 },
        { q: "Which French military leader crowned himself emperor in 1804?", options: ["Louis XIV", "Napoleon Bonaparte", "Maximilien Robespierre", "Charles de Gaulle"], correct: 1 },
        { q: "Who was the first human in space?", options: ["Yuri Gagarin", "Neil Armstrong", "Alan Shepard", "John Glenn"], correct: 0 },
        { q: "Which civilization used hieroglyphics?", options: ["Romans", "Phoenicians", "Ancient Egyptians", "Persians"], correct: 2 },
        { q: "Who was the last tsar of Russia?", options: ["Peter the Great", "Nicholas II", "Alexander III", "Ivan IV"], correct: 1 },
        { q: "The Protestant Reformation is closely associated with which figure?", options: ["John Calvin", "Martin Luther", "Thomas More", "Erasmus"], correct: 1 },
        { q: "What year did the stock market crash that helped trigger the Great Depression occur?", options: ["1918", "1929", "1933", "1939"], correct: 1 },
        { q: "Which document begins with the words 'We the People'?", options: ["Declaration of Independence", "U.S. Constitution", "Bill of Rights", "Emancipation Proclamation"], correct: 1 },
        { q: "Who was the first female prime minister of the United Kingdom?", options: ["Theresa May", "Margaret Thatcher", "Indira Gandhi", "Golda Meir"], correct: 1 },
        { q: "Which civilization built the city of Tenochtitlan?", options: ["Inca", "Aztec", "Maya", "Toltec"], correct: 1 },
        { q: "In what year did Constantinople fall to the Ottomans?", options: ["1066", "1453", "1492", "1521"], correct: 1 },
        { q: "Who wrote the Communist Manifesto with Friedrich Engels?", options: ["Vladimir Lenin", "Karl Marx", "Mikhail Bakunin", "Leon Trotsky"], correct: 1 },
        { q: "Which battle in 1815 marked Napoleon's final defeat?", options: ["Austerlitz", "Trafalgar", "Waterloo", "Leipzig"], correct: 2 },
        { q: "Who was the first Tudor king of England?", options: ["Henry VII", "Henry VIII", "Edward VI", "Richard III"], correct: 0 },
        { q: "Which pandemic killed millions in 14th-century Europe?", options: ["Spanish flu", "Black Death", "Smallpox", "Cholera"], correct: 1 },
        { q: "What was the name of the trade route connecting China to the Mediterranean?", options: ["Amber Road", "Silk Road", "Spice Route", "Royal Road"], correct: 1 },
        { q: "Who was the first emperor of a unified China?", options: ["Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Han Wudi"], correct: 0 },
        { q: "Which U.S. president issued the Emancipation Proclamation?", options: ["Andrew Jackson", "Abraham Lincoln", "Ulysses S. Grant", "James Buchanan"], correct: 1 },
        { q: "The D-Day landings took place in which year?", options: ["1942", "1943", "1944", "1945"], correct: 2 },
        { q: "Who was the first man to reach the South Pole?", options: ["Robert Falcon Scott", "Roald Amundsen", "Ernest Shackleton", "Edmund Hillary"], correct: 1 },
        { q: "Which empire was centered in modern-day Peru before Spanish conquest?", options: ["Maya", "Aztec", "Inca", "Moche"], correct: 2 },
        { q: "Who was the queen of ancient Egypt who allied with Julius Caesar and Mark Antony?", options: ["Hatshepsut", "Cleopatra", "Nefertiti", "Boudica"], correct: 1 },
        { q: "Which treaty ended World War I?", options: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Tordesillas", "Treaty of Utrecht"], correct: 1 },
        { q: "Who was the first European explorer to reach India by sea via the Cape of Good Hope?", options: ["Vasco da Gama", "Bartolomeu Dias", "Christopher Columbus", "Amerigo Vespucci"], correct: 0 },
        { q: "What year did women gain the right to vote nationally in the United States?", options: ["1910", "1920", "1930", "1945"], correct: 1 },
        { q: "Which U.S. scandal caused President Richard Nixon to resign?", options: ["Teapot Dome", "Iran-Contra", "Watergate", "Whitewater"], correct: 2 },
        { q: "Who was the Carthaginian general who crossed the Alps with elephants?", options: ["Scipio", "Hannibal", "Augustus", "Pericles"], correct: 1 },
        { q: "Which civilization is associated with the city of Sparta?", options: ["Roman", "Greek", "Persian", "Phoenician"], correct: 1 },
        { q: "What year did the Cold War end with the dissolution of the Soviet Union?", options: ["1989", "1991", "1993", "1995"], correct: 1 },
        { q: "Who was the first president of the Russian Federation?", options: ["Mikhail Gorbachev", "Boris Yeltsin", "Vladimir Putin", "Dmitry Medvedev"], correct: 1 },
        { q: "Which war was fought between Athens and Sparta?", options: ["Punic Wars", "Peloponnesian War", "Hundred Years' War", "Crimean War"], correct: 1 },
        { q: "Who was the first woman to win a Nobel Prize?", options: ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Jane Addams"], correct: 0 },
        { q: "Which civilization built Chichen Itza?", options: ["Aztec", "Maya", "Inca", "Olmec"], correct: 1 },
        { q: "Who became U.S. president after John F. Kennedy was assassinated?", options: ["Lyndon B. Johnson", "Richard Nixon", "Hubert Humphrey", "Gerald Ford"], correct: 0 },
        { q: "The Hundred Years' War was mainly fought between England and which country?", options: ["Spain", "France", "Germany", "Italy"], correct: 1 },
        { q: "Who was the founder of the Mongol Empire?", options: ["Kublai Khan", "Tamerlane", "Genghis Khan", "Attila"], correct: 2 },
        { q: "What ancient code of laws is associated with Babylon?", options: ["Justinian Code", "Code of Hammurabi", "Twelve Tables", "Draco's Code"], correct: 1 },
        { q: "Which pharaoh is famous for his tomb discovered in 1922?", options: ["Ramesses II", "Tutankhamun", "Akhenaten", "Khufu"], correct: 1 },
        { q: "Who led the Haitian Revolution?", options: ["Toussaint Louverture", "Simon Bolivar", "Jean-Jacques Dessalines", "Che Guevara"], correct: 0 },
        { q: "Which empire was ruled by Mansa Musa?", options: ["Mali Empire", "Songhai Empire", "Ottoman Empire", "Mughal Empire"], correct: 0 },
        { q: "What year did the Chernobyl disaster occur?", options: ["1979", "1984", "1986", "1989"], correct: 2 },
        { q: "Who was the first ruler of the Mughal Empire in India?", options: ["Akbar", "Babur", "Shah Jahan", "Aurangzeb"], correct: 1 },
        { q: "Which U.S. president launched the New Deal?", options: ["Herbert Hoover", "Franklin D. Roosevelt", "Harry Truman", "Woodrow Wilson"], correct: 1 },
        { q: "What was the name of the first artificial satellite launched into space?", options: ["Apollo 1", "Sputnik 1", "Vostok 1", "Explorer 1"], correct: 1 },
        { q: "Who was the first Roman emperor to convert to Christianity?", options: ["Nero", "Constantine", "Hadrian", "Marcus Aurelius"], correct: 1 },
        { q: "Which city served as the capital of the Byzantine Empire?", options: ["Athens", "Rome", "Constantinople", "Antioch"], correct: 2 },
        { q: "Who was the first European to see the Pacific Ocean from the Americas?", options: ["Vasco Nunez de Balboa", "Hernan Cortes", "Francisco Pizarro", "Hernando de Soto"], correct: 0 },
        { q: "What year did the first successful powered flight by the Wright brothers occur?", options: ["1899", "1903", "1908", "1911"], correct: 1 },
        { q: "Which ancient wonder stood at the harbor of Rhodes?", options: ["Colossus of Rhodes", "Lighthouse of Alexandria", "Temple of Artemis", "Statue of Zeus"], correct: 0 },
        { q: "Who was the first female ruler of Russia to be called 'the Great'?", options: ["Catherine the Great", "Elizabeth I of Russia", "Anastasia", "Maria Theresa"], correct: 0 },
        { q: "Which war was fought in the 1950s between North Korea and South Korea?", options: ["Vietnam War", "Korean War", "Cold War", "Sino-Japanese War"], correct: 1 },
        { q: "Who led the Soviet Union during the Cuban Missile Crisis?", options: ["Joseph Stalin", "Mikhail Gorbachev", "Nikita Khrushchev", "Leonid Brezhnev"], correct: 2 },
        { q: "What year did the French Revolution's Reign of Terror begin?", options: ["1789", "1791", "1793", "1799"], correct: 2 },
        { q: "Which ancient Greek philosopher taught Alexander the Great?", options: ["Socrates", "Plato", "Aristotle", "Pythagoras"], correct: 2 },
        { q: "Who was the first man to summit Mount Everest with Tenzing Norgay?", options: ["Edmund Hillary", "Reinhold Messner", "George Mallory", "Ranulph Fiennes"], correct: 0 },
        { q: "Which war featured the Battle of Gettysburg?", options: ["War of 1812", "American Civil War", "Mexican-American War", "Revolutionary War"], correct: 1 },
        { q: "Who was the first emperor of the French after the Revolution?", options: ["Louis XVI", "Napoleon Bonaparte", "Charles X", "Louis Philippe"], correct: 1 },
        { q: "Which ancient people built roads across their empire and are famous for legions?", options: ["Persians", "Romans", "Phoenicians", "Gauls"], correct: 1 },
        { q: "What year did the United Nations officially begin operations?", options: ["1942", "1945", "1948", "1950"], correct: 1 },
        { q: "Who wrote the '95 Theses'?", options: ["Martin Luther", "John Wycliffe", "Thomas Cranmer", "Jan Hus"], correct: 0 },
        { q: "Which emperor built much of the Mughal architecture including the Red Fort's era of expansion?", options: ["Babur", "Akbar", "Shah Jahan", "Humayun"], correct: 1 },
        { q: "Who was the first female pharaoh of ancient Egypt?", options: ["Cleopatra", "Hatshepsut", "Nefertiti", "Sobekneferu"], correct: 3 },
        { q: "Which battle in 1066 changed English history dramatically?", options: ["Battle of Hastings", "Battle of Agincourt", "Battle of Bosworth", "Battle of Tours"], correct: 0 },
        { q: "Who was the first chancellor of a unified Germany?", options: ["Kaiser Wilhelm II", "Otto von Bismarck", "Helmut Kohl", "Frederick the Great"], correct: 1 },
        { q: "Which civilization created cuneiform writing?", options: ["Sumerians", "Egyptians", "Minoans", "Hittites"], correct: 0 },
        { q: "What year did the Soviet Union launch Sputnik 1?", options: ["1955", "1957", "1961", "1963"], correct: 1 },
        { q: "Who was the first woman in space?", options: ["Valentina Tereshkova", "Svetlana Savitskaya", "Sally Ride", "Mae Jemison"], correct: 0 },
        { q: "Which conflict was known as the Great War before World War II?", options: ["Crimean War", "World War I", "Franco-Prussian War", "Russo-Japanese War"], correct: 1 },
        { q: "Who was the first Muslim ruler to conquer Constantinople?", options: ["Mehmed II", "Suleiman the Magnificent", "Selim I", "Bayezid I"], correct: 0 },
        { q: "What was the name of the ship Charles Darwin sailed on?", options: ["HMS Victory", "HMS Beagle", "Mayflower", "Endeavour"], correct: 1 },
        { q: "Which leader delivered the 'I Have a Dream' speech in 1963?", options: ["Malcolm X", "Martin Luther King Jr.", "John Lewis", "Thurgood Marshall"], correct: 1 },
        { q: "Which empire used the city of Cusco as a capital?", options: ["Aztec", "Inca", "Maya", "Olmec"], correct: 1 },
        { q: "Who was the first U.S. president to resign from office?", options: ["Richard Nixon", "Herbert Hoover", "Gerald Ford", "Lyndon B. Johnson"], correct: 0 },
        { q: "Which rebellion in China was led by Hong Xiuquan?", options: ["Boxer Rebellion", "Taiping Rebellion", "Opium War", "Xinhai Revolution"], correct: 1 }
    ],
    'Art & Literature': [
        { q: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correct: 1 },
        { q: "Who painted the Mona Lisa?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Botticelli"], correct: 2 },
        { q: "What is the name of the famous painting by Edvard Munch?", options: ["The Scream", "Starry Night", "The Kiss", "Girl with Pearl Earring"], correct: 0 },
        { q: "Who wrote '1984'?", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"], correct: 1 },
        { q: "Which artist cut off part of his own ear?", options: ["Pablo Picasso", "Claude Monet", "Vincent van Gogh", "Salvador Dalí"], correct: 2 },
        { q: "Who wrote 'Pride and Prejudice'?", options: ["Charlotte Brontë", "Emily Brontë", "Jane Austen", "Mary Shelley"], correct: 2 },
        { q: "The Sistine Chapel ceiling was painted by whom?", options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], correct: 1 },
        { q: "Who wrote 'The Great Gatsby'?", options: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"], correct: 1 },
        { q: "Which art movement is Salvador Dalí associated with?", options: ["Impressionism", "Cubism", "Surrealism", "Pop Art"], correct: 2 },
        { q: "Who wrote 'Don Quixote'?", options: ["Miguel de Cervantes", "Gabriel García Márquez", "Jorge Luis Borges", "Pablo Neruda"], correct: 0 },
        { q: "Who painted 'Starry Night'?", options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Paul Cezanne"], correct: 1 },
        { q: "Who wrote 'To Kill a Mockingbird'?", options: ["Harper Lee", "Toni Morrison", "Flannery O'Connor", "Carson McCullers"], correct: 0 },
        { q: "Which artist painted 'The Persistence of Memory'?", options: ["Pablo Picasso", "Salvador Dali", "Henri Matisse", "Paul Klee"], correct: 1 },
        { q: "Who wrote 'Moby-Dick'?", options: ["Nathaniel Hawthorne", "Herman Melville", "Mark Twain", "Henry James"], correct: 1 },
        { q: "Which playwright wrote 'Hamlet'?", options: ["Christopher Marlowe", "William Shakespeare", "Ben Jonson", "Oscar Wilde"], correct: 1 },
        { q: "Who painted 'The Last Supper'?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Titian"], correct: 2 },
        { q: "Who wrote 'The Catcher in the Rye'?", options: ["J.D. Salinger", "John Steinbeck", "F. Scott Fitzgerald", "Kurt Vonnegut"], correct: 0 },
        { q: "Which artist is famous for the 'Campbell's Soup Cans' works?", options: ["Roy Lichtenstein", "Andy Warhol", "Jackson Pollock", "Keith Haring"], correct: 1 },
        { q: "Who wrote 'Jane Eyre'?", options: ["Emily Bronte", "Charlotte Bronte", "Jane Austen", "George Eliot"], correct: 1 },
        { q: "Which sculptor created 'David' during the Renaissance?", options: ["Donatello", "Bernini", "Michelangelo", "Rodin"], correct: 2 },
        { q: "Who wrote 'The Odyssey'?", options: ["Sophocles", "Virgil", "Homer", "Ovid"], correct: 2 },
        { q: "Which painter is associated with the Blue Period?", options: ["Picasso", "Miro", "Dali", "Goya"], correct: 0 },
        { q: "Who wrote 'The Divine Comedy'?", options: ["Dante Alighieri", "Giovanni Boccaccio", "Petrarch", "Torquato Tasso"], correct: 0 },
        { q: "Which artist painted 'Guernica'?", options: ["Salvador Dali", "Pablo Picasso", "Diego Rivera", "Francisco Goya"], correct: 1 },
        { q: "Who wrote 'Brave New World'?", options: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "H.G. Wells"], correct: 1 },
        { q: "Which author created Sherlock Holmes?", options: ["Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "G.K. Chesterton"], correct: 1 },
        { q: "Which artist painted 'The Birth of Venus'?", options: ["Botticelli", "Raphael", "Leonardo da Vinci", "Caravaggio"], correct: 0 },
        { q: "Who wrote 'The Hobbit'?", options: ["C.S. Lewis", "J.R.R. Tolkien", "T.H. White", "Philip Pullman"], correct: 1 },
        { q: "Which poet wrote 'The Raven'?", options: ["Walt Whitman", "Edgar Allan Poe", "Robert Frost", "Emily Dickinson"], correct: 1 },
        { q: "Which painter is known for drip painting?", options: ["Mark Rothko", "Jackson Pollock", "Wassily Kandinsky", "Piet Mondrian"], correct: 1 },
        { q: "Who wrote 'Crime and Punishment'?", options: ["Leo Tolstoy", "Anton Chekhov", "Fyodor Dostoevsky", "Ivan Turgenev"], correct: 2 },
        { q: "Which artist painted 'Girl with a Pearl Earring'?", options: ["Johannes Vermeer", "Rembrandt", "Jan van Eyck", "Frans Hals"], correct: 0 },
        { q: "Who wrote 'The Picture of Dorian Gray'?", options: ["Oscar Wilde", "Bram Stoker", "Thomas Hardy", "Charles Dickens"], correct: 0 },
        { q: "Which playwright wrote 'A Doll's House'?", options: ["Henrik Ibsen", "Anton Chekhov", "August Strindberg", "George Bernard Shaw"], correct: 0 },
        { q: "Which author wrote 'The Brothers Karamazov'?", options: ["Nikolai Gogol", "Fyodor Dostoevsky", "Leo Tolstoy", "Maxim Gorky"], correct: 1 },
        { q: "Which painter is famous for water lilies?", options: ["Edgar Degas", "Claude Monet", "Paul Gauguin", "Pierre-Auguste Renoir"], correct: 1 },
        { q: "Who wrote 'Wuthering Heights'?", options: ["Emily Bronte", "Charlotte Bronte", "Anne Bronte", "Mary Shelley"], correct: 0 },
        { q: "Which author wrote 'The Old Man and the Sea'?", options: ["John Steinbeck", "Ernest Hemingway", "William Faulkner", "F. Scott Fitzgerald"], correct: 1 },
        { q: "Which artist painted 'The Night Watch'?", options: ["Vermeer", "Rembrandt", "Rubens", "El Greco"], correct: 1 },
        { q: "Who wrote 'Frankenstein'?", options: ["Mary Shelley", "Bram Stoker", "Ann Radcliffe", "Emily Bronte"], correct: 0 },
        { q: "Which painter is known for melting clocks?", options: ["Pablo Picasso", "Salvador Dali", "Joan Miro", "Marc Chagall"], correct: 1 },
        { q: "Who wrote 'One Hundred Years of Solitude'?", options: ["Jorge Luis Borges", "Julio Cortazar", "Gabriel Garcia Marquez", "Mario Vargas Llosa"], correct: 2 },
        { q: "Which artist painted 'American Gothic'?", options: ["Edward Hopper", "Grant Wood", "Thomas Hart Benton", "Andrew Wyeth"], correct: 1 },
        { q: "Who wrote 'The Iliad'?", options: ["Homer", "Virgil", "Aeschylus", "Sophocles"], correct: 0 },
        { q: "Which painter was a leading figure of Cubism with Picasso?", options: ["Georges Braque", "Henri Rousseau", "Paul Klee", "Amedeo Modigliani"], correct: 0 },
        { q: "Who wrote 'Anna Karenina'?", options: ["Leo Tolstoy", "Fyodor Dostoevsky", "Ivan Turgenev", "Anton Chekhov"], correct: 0 },
        { q: "Which artist made the sculpture 'The Thinker'?", options: ["Michelangelo", "Auguste Rodin", "Donatello", "Henry Moore"], correct: 1 },
        { q: "Who wrote 'The Sun Also Rises'?", options: ["Ernest Hemingway", "John Steinbeck", "F. Scott Fitzgerald", "Sinclair Lewis"], correct: 0 },
        { q: "Which author wrote 'Beloved'?", options: ["Toni Morrison", "Alice Walker", "Maya Angelou", "Zora Neale Hurston"], correct: 0 },
        { q: "Which artist painted 'Las Meninas'?", options: ["El Greco", "Diego Velazquez", "Francisco Goya", "Bartolome Murillo"], correct: 1 },
        { q: "Who wrote 'Lolita'?", options: ["Boris Pasternak", "Vladimir Nabokov", "Aleksandr Solzhenitsyn", "Milan Kundera"], correct: 1 },
        { q: "Which painter is known for self-portraits and unibrow iconography?", options: ["Georgia O'Keeffe", "Frida Kahlo", "Tamara de Lempicka", "Berthe Morisot"], correct: 1 },
        { q: "Who wrote 'The Grapes of Wrath'?", options: ["John Steinbeck", "Ernest Hemingway", "William Faulkner", "John Dos Passos"], correct: 0 },
        { q: "Which poet wrote 'Leaves of Grass'?", options: ["Walt Whitman", "T.S. Eliot", "Ezra Pound", "Langston Hughes"], correct: 0 },
        { q: "Which artist painted 'The Kiss' in a gold-leaf style?", options: ["Egon Schiele", "Gustav Klimt", "Oskar Kokoschka", "Alphonse Mucha"], correct: 1 },
        { q: "Who wrote 'Dracula'?", options: ["Mary Shelley", "Bram Stoker", "H.G. Wells", "Arthur Machen"], correct: 1 },
        { q: "Which author wrote 'The Trial'?", options: ["Franz Kafka", "Thomas Mann", "Hermann Hesse", "Albert Camus"], correct: 0 },
        { q: "Which painter created 'Nighthawks'?", options: ["Edward Hopper", "Norman Rockwell", "Grant Wood", "Winslow Homer"], correct: 0 },
        { q: "Who wrote 'Heart of Darkness'?", options: ["Joseph Conrad", "Rudyard Kipling", "E.M. Forster", "Graham Greene"], correct: 0 },
        { q: "Which author wrote 'A Tale of Two Cities'?", options: ["Charles Dickens", "Thomas Hardy", "William Makepeace Thackeray", "George Eliot"], correct: 0 },
        { q: "Which artist is known for painting ballerinas?", options: ["Edgar Degas", "Claude Monet", "Henri Matisse", "Paul Cezanne"], correct: 0 },
        { q: "Who wrote 'The Name of the Rose'?", options: ["Italo Calvino", "Umberto Eco", "Elena Ferrante", "Primo Levi"], correct: 1 },
        { q: "Which playwright wrote 'Waiting for Godot'?", options: ["Samuel Beckett", "Eugene Ionesco", "Harold Pinter", "Jean Genet"], correct: 0 },
        { q: "Which author wrote 'The Metamorphosis'?", options: ["Franz Kafka", "Hermann Hesse", "Thomas Mann", "Rainer Maria Rilke"], correct: 0 },
        { q: "Which painter is known for haystacks and Rouen Cathedral series?", options: ["Claude Monet", "Camille Pissarro", "Paul Signac", "Alfred Sisley"], correct: 0 },
        { q: "Who wrote 'Invisible Man'?", options: ["Ralph Ellison", "Richard Wright", "James Baldwin", "Langston Hughes"], correct: 0 },
        { q: "Which sculptor created 'The Kiss' in marble?", options: ["Auguste Rodin", "Gian Lorenzo Bernini", "Antonio Canova", "Constantin Brancusi"], correct: 0 },
        { q: "Who wrote 'Mrs Dalloway'?", options: ["Virginia Woolf", "Doris Lessing", "George Eliot", "Jean Rhys"], correct: 0 },
        { q: "Which painter was a founder of Fauvism?", options: ["Henri Matisse", "Paul Klee", "Paul Cezanne", "Edvard Munch"], correct: 0 },
        { q: "Who wrote 'War and Peace'?", options: ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Boris Pasternak"], correct: 0 },
        { q: "Which artist designed much of the Sagrada Familia?", options: ["Pablo Picasso", "Antoni Gaudi", "Santiago Calatrava", "Joan Miro"], correct: 1 },
        { q: "Who wrote 'The Stranger'?", options: ["Jean-Paul Sartre", "Albert Camus", "Andre Gide", "Simone de Beauvoir"], correct: 1 },
        { q: "Which painter is famous for geometric compositions with primary colors?", options: ["Piet Mondrian", "Wassily Kandinsky", "Paul Klee", "Kazimir Malevich"], correct: 0 },
        { q: "Who wrote 'The Sound and the Fury'?", options: ["William Faulkner", "John Steinbeck", "Ernest Hemingway", "Sherwood Anderson"], correct: 0 },
        { q: "Which poet wrote 'The Waste Land'?", options: ["W.B. Yeats", "T.S. Eliot", "Ezra Pound", "Robert Frost"], correct: 1 },
        { q: "Which artist painted 'The Sleeping Gypsy'?", options: ["Henri Rousseau", "Paul Gauguin", "Paul Cezanne", "Georges Seurat"], correct: 0 },
        { q: "Who wrote 'Don Juan' as a satirical epic poem?", options: ["John Keats", "Lord Byron", "Percy Bysshe Shelley", "William Blake"], correct: 1 },
        { q: "Which author wrote 'Their Eyes Were Watching God'?", options: ["Toni Morrison", "Alice Walker", "Zora Neale Hurston", "Maya Angelou"], correct: 2 },
        { q: "Which painter is associated with pointillism and painted 'A Sunday Afternoon on the Island of La Grande Jatte'?", options: ["Georges Seurat", "Paul Signac", "Camille Pissarro", "Henri de Toulouse-Lautrec"], correct: 0 },
        { q: "Who wrote 'The Road'?", options: ["Cormac McCarthy", "Don DeLillo", "Philip Roth", "Thomas Pynchon"], correct: 0 },
        { q: "Which author wrote 'The Handmaid's Tale'?", options: ["Margaret Atwood", "Doris Lessing", "Jeanette Winterson", "Angela Carter"], correct: 0 },
        { q: "Which artist painted 'The School of Athens'?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Titian"], correct: 1 },
        { q: "Who wrote 'The Importance of Being Earnest'?", options: ["George Bernard Shaw", "Oscar Wilde", "Noel Coward", "Richard Sheridan"], correct: 1 },
        { q: "Which artist is famous for mobiles and stabiles?", options: ["Constantin Brancusi", "Alexander Calder", "Henry Moore", "Alberto Giacometti"], correct: 1 },
        { q: "Who wrote 'Things Fall Apart'?", options: ["Wole Soyinka", "Chinua Achebe", "Ngugi wa Thiong'o", "Ben Okri"], correct: 1 },
        { q: "Which painter created 'Whistler's Mother'?", options: ["John Singer Sargent", "James McNeill Whistler", "Thomas Eakins", "Winslow Homer"], correct: 1 },
        { q: "Who wrote 'Rebecca'?", options: ["Daphne du Maurier", "Agatha Christie", "Iris Murdoch", "Patricia Highsmith"], correct: 0 },
        { q: "Which author wrote 'A Passage to India'?", options: ["E.M. Forster", "Rudyard Kipling", "Graham Greene", "Salman Rushdie"], correct: 0 },
        { q: "Which artist painted 'Bal du moulin de la Galette'?", options: ["Edgar Degas", "Pierre-Auguste Renoir", "Claude Monet", "Henri Matisse"], correct: 1 },
        { q: "Who wrote 'The Bell Jar'?", options: ["Sylvia Plath", "Anne Sexton", "Joan Didion", "Maya Angelou"], correct: 0 },
        { q: "Which playwright wrote 'Death of a Salesman'?", options: ["Tennessee Williams", "Arthur Miller", "Eugene O'Neill", "Edward Albee"], correct: 1 },
        { q: "Which artist painted 'Olympia'?", options: ["Edouard Manet", "Claude Monet", "Edgar Degas", "Paul Cezanne"], correct: 0 },
        { q: "Who wrote 'The Color Purple'?", options: ["Alice Walker", "Toni Morrison", "Maya Angelou", "Zadie Smith"], correct: 0 },
        { q: "Which poet wrote 'Because I could not stop for Death'?", options: ["Emily Dickinson", "Sylvia Plath", "Elizabeth Barrett Browning", "Maya Angelou"], correct: 0 },
        { q: "Which artist made the sculpture 'Bird in Space'?", options: ["Henry Moore", "Alberto Giacometti", "Constantin Brancusi", "Alexander Calder"], correct: 2 },
        { q: "Who wrote 'Les Miserables'?", options: ["Victor Hugo", "Honore de Balzac", "Alexandre Dumas", "Emile Zola"], correct: 0 },
        { q: "Which painter is associated with the mural 'Detroit Industry'?", options: ["Diego Rivera", "Jose Clemente Orozco", "David Alfaro Siqueiros", "Frida Kahlo"], correct: 0 },
        { q: "Who wrote 'Fahrenheit 451'?", options: ["Ray Bradbury", "Kurt Vonnegut", "Isaac Asimov", "Philip K. Dick"], correct: 0 },
        { q: "Which author wrote 'Middlemarch'?", options: ["George Eliot", "Jane Austen", "Charlotte Bronte", "Virginia Woolf"], correct: 0 },
        { q: "Which artist painted 'Liberty Leading the People'?", options: ["Eugene Delacroix", "Jacques-Louis David", "Theodore Gericault", "Jean-Auguste-Dominique Ingres"], correct: 0 },
        { q: "Who wrote 'The Left Hand of Darkness'?", options: ["Octavia Butler", "Ursula K. Le Guin", "Margaret Atwood", "Madeleine L'Engle"], correct: 1 },
        { q: "Which novelist wrote 'Slaughterhouse-Five'?", options: ["Joseph Heller", "Kurt Vonnegut", "Thomas Pynchon", "Don DeLillo"], correct: 1 },
        { q: "Which painter created 'Impression, Sunrise'?", options: ["Claude Monet", "Pierre-Auguste Renoir", "Camille Pissarro", "Berthe Morisot"], correct: 0 },
        { q: "Who wrote 'Oedipus Rex'?", options: ["Euripides", "Aristophanes", "Sophocles", "Aeschylus"], correct: 2 },
        { q: "Which artist is famous for the giant spider sculpture 'Maman'?", options: ["Yayoi Kusama", "Louise Bourgeois", "Barbara Hepworth", "Niki de Saint Phalle"], correct: 1 }
    ],
    'Science & Nature': [
        { q: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correct: 2 },
        { q: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correct: 1 },
        { q: "What is the largest mammal on Earth?", options: ["African Elephant", "Blue Whale", "Giraffe", "Polar Bear"], correct: 1 },
        { q: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], correct: 2 },
        { q: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], correct: 2 },
        { q: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], correct: 1 },
        { q: "What is the speed of light approximately?", options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s"], correct: 0 },
        { q: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correct: 1 },
        { q: "What is the largest organ in the human body?", options: ["Liver", "Brain", "Skin", "Heart"], correct: 2 },
        { q: "What element does 'O' represent on the periodic table?", options: ["Osmium", "Oxygen", "Oganesson", "Oxide"], correct: 1 },
        { q: "What planet is closest to the Sun?", options: ["Venus", "Mars", "Mercury", "Earth"], correct: 2 },
        { q: "What force keeps planets in orbit around the Sun?", options: ["Magnetism", "Gravity", "Friction", "Electricity"], correct: 1 },
        { q: "Which gas is most abundant in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen"], correct: 3 },
        { q: "What is H2O commonly known as?", options: ["Salt", "Oxygen", "Water", "Hydrogen"], correct: 2 },
        { q: "What part of the cell contains genetic material?", options: ["Membrane", "Nucleus", "Ribosome", "Cytoplasm"], correct: 1 },
        { q: "Which blood type is known as the universal donor?", options: ["AB positive", "O negative", "A positive", "B negative"], correct: 1 },
        { q: "What is the nearest star to Earth?", options: ["Sirius", "Proxima Centauri", "The Sun", "Betelgeuse"], correct: 2 },
        { q: "What is the process by which plants make food?", options: ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], correct: 1 },
        { q: "What is the boiling point of water at sea level in Celsius?", options: ["90", "95", "100", "110"], correct: 2 },
        { q: "What organ pumps blood through the human body?", options: ["Lungs", "Liver", "Brain", "Heart"], correct: 3 },
        { q: "Which planet has the most prominent ring system?", options: ["Mars", "Jupiter", "Saturn", "Neptune"], correct: 2 },
        { q: "What is the smallest unit of matter?", options: ["Atom", "Cell", "Molecule", "Electron"], correct: 0 },
        { q: "Which vitamin is mainly produced by the skin in sunlight?", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], correct: 2 },
        { q: "What is the main gas that humans breathe out?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], correct: 1 },
        { q: "Which planet is the largest in our solar system?", options: ["Saturn", "Jupiter", "Neptune", "Earth"], correct: 1 },
        { q: "What scale is used to measure earthquake magnitude commonly in basic quizzes?", options: ["Celsius scale", "Richter scale", "Beaufort scale", "Mohs scale"], correct: 1 },
        { q: "What do bees collect from flowers to make honey?", options: ["Pollen only", "Nectar", "Sap", "Water"], correct: 1 },
        { q: "What type of animal is a Komodo dragon?", options: ["Mammal", "Bird", "Reptile", "Amphibian"], correct: 2 },
        { q: "Which planet is famous for its Great Red Spot?", options: ["Mars", "Jupiter", "Venus", "Uranus"], correct: 1 },
        { q: "How many teeth does a typical adult human have?", options: ["28", "30", "32", "34"], correct: 2 },
        { q: "Which metal is liquid at room temperature?", options: ["Mercury", "Silver", "Lead", "Tin"], correct: 0 },
        { q: "What is the center of an atom called?", options: ["Shell", "Core", "Nucleus", "Proton"], correct: 2 },
        { q: "Which organ is primarily responsible for filtering blood?", options: ["Kidneys", "Stomach", "Lungs", "Pancreas"], correct: 0 },
        { q: "What phenomenon causes the sky to appear blue?", options: ["Reflection", "Refraction", "Rayleigh scattering", "Absorption"], correct: 2 },
        { q: "Which planet rotates on its side?", options: ["Venus", "Uranus", "Mercury", "Mars"], correct: 1 },
        { q: "What is the scientific name for animals without backbones?", options: ["Vertebrates", "Invertebrates", "Arthropods", "Mollusks"], correct: 1 },
        { q: "Which gas do humans need to breathe to survive?", options: ["Hydrogen", "Nitrogen", "Oxygen", "Helium"], correct: 2 },
        { q: "What is the hardest substance in the human body?", options: ["Bone", "Tooth enamel", "Nail", "Cartilage"], correct: 1 },
        { q: "What is the primary source of energy for Earth's climate system?", options: ["The Moon", "Earth's core", "The Sun", "Ocean currents"], correct: 2 },
        { q: "Which type of blood cells help fight infection?", options: ["Red blood cells", "White blood cells", "Platelets", "Plasma cells"], correct: 1 },
        { q: "What part of the eye controls how much light enters?", options: ["Retina", "Pupil", "Cornea", "Lens"], correct: 1 },
        { q: "Which planet is known for being the hottest in our solar system?", options: ["Mercury", "Venus", "Mars", "Jupiter"], correct: 1 },
        { q: "What is the chemical symbol for sodium?", options: ["S", "So", "Na", "Sd"], correct: 2 },
        { q: "Which branch of science studies living things?", options: ["Physics", "Geology", "Biology", "Astronomy"], correct: 2 },
        { q: "What is the process of a liquid turning into a gas called?", options: ["Condensation", "Evaporation", "Freezing", "Melting"], correct: 1 },
        { q: "Which planet is farthest from the Sun?", options: ["Saturn", "Uranus", "Neptune", "Pluto"], correct: 2 },
        { q: "What is the largest planet's most famous moon called?", options: ["Titan", "Europa", "Ganymede", "Io"], correct: 2 },
        { q: "Which animal is the largest land mammal?", options: ["White rhino", "Hippo", "African elephant", "Giraffe"], correct: 2 },
        { q: "What is the pH of pure water at room temperature?", options: ["5", "6", "7", "8"], correct: 2 },
        { q: "Which layer of Earth is made of molten rock?", options: ["Crust", "Mantle", "Inner core", "Atmosphere"], correct: 1 },
        { q: "What type of celestial body is Halley's object commonly called?", options: ["Asteroid", "Comet", "Meteor", "Moon"], correct: 1 },
        { q: "Which planet has the shortest year?", options: ["Mercury", "Venus", "Earth", "Mars"], correct: 0 },
        { q: "What is the human body's largest internal organ?", options: ["Brain", "Liver", "Lung", "Kidney"], correct: 1 },
        { q: "Which scientist proposed the three laws of motion?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], correct: 1 },
        { q: "What is the unit used to measure electric current?", options: ["Volt", "Watt", "Ampere", "Ohm"], correct: 2 },
        { q: "What kind of rock is formed from cooled lava?", options: ["Sedimentary", "Metamorphic", "Igneous", "Fossil"], correct: 2 },
        { q: "Which planet is sometimes called Earth's twin because of similar size?", options: ["Mars", "Venus", "Mercury", "Neptune"], correct: 1 },
        { q: "What blood vessels carry blood away from the heart?", options: ["Veins", "Arteries", "Capillaries", "Valves"], correct: 1 },
        { q: "Which particle has a negative electric charge?", options: ["Proton", "Neutron", "Electron", "Photon"], correct: 2 },
        { q: "What type of eclipse occurs when the Moon moves between Earth and the Sun?", options: ["Lunar eclipse", "Solar eclipse", "Annular tide", "Meteor shower"], correct: 1 },
        { q: "What is the study of weather called?", options: ["Meteorology", "Seismology", "Ecology", "Volcanology"], correct: 0 },
        { q: "Which organ helps humans breathe by exchanging gases with the blood?", options: ["Heart", "Lungs", "Liver", "Spleen"], correct: 1 },
        { q: "What is the main component of the Sun?", options: ["Oxygen", "Carbon", "Hydrogen", "Iron"], correct: 2 },
        { q: "Which planet has the tallest known volcano in the solar system?", options: ["Venus", "Mars", "Earth", "Jupiter"], correct: 1 },
        { q: "What mineral is rated 10 on the Mohs hardness scale?", options: ["Quartz", "Topaz", "Corundum", "Diamond"], correct: 3 },
        { q: "What is the function of red blood cells?", options: ["Fight infection", "Carry oxygen", "Digest food", "Make hormones"], correct: 1 },
        { q: "Which scientific instrument is used to look at stars and planets?", options: ["Microscope", "Periscope", "Telescope", "Barometer"], correct: 2 },
        { q: "What kind of energy is stored in food?", options: ["Nuclear energy", "Chemical energy", "Sound energy", "Light energy"], correct: 1 },
        { q: "Which gas is used by plants during photosynthesis and released by humans?", options: ["Oxygen", "Helium", "Carbon Dioxide", "Argon"], correct: 2 },
        { q: "What type of joint is the shoulder?", options: ["Hinge joint", "Ball-and-socket joint", "Pivot joint", "Gliding joint"], correct: 1 },
        { q: "Which scientist developed the theory of evolution by natural selection?", options: ["Gregor Mendel", "Louis Pasteur", "Charles Darwin", "Carl Linnaeus"], correct: 2 },
        { q: "What is a group of lions called?", options: ["Pack", "Herd", "Pride", "Swarm"], correct: 2 },
        { q: "What is the freezing point of water in Celsius?", options: ["0", "10", "32", "100"], correct: 0 },
        { q: "Which organ system includes the brain and spinal cord?", options: ["Circulatory system", "Digestive system", "Nervous system", "Muscular system"], correct: 2 },
        { q: "What does DNA stand for?", options: ["Dynamic Nucleic Acid", "Deoxyribonucleic Acid", "Dual Nitrogen Atom", "Deoxynuclear Acid"], correct: 1 },
        { q: "Which planet is known for its many moons and giant size?", options: ["Jupiter", "Mercury", "Venus", "Mars"], correct: 0 },
        { q: "What do you call animals that eat both plants and animals?", options: ["Carnivores", "Herbivores", "Omnivores", "Scavengers"], correct: 2 },
        { q: "Which part of a plant usually absorbs water from the soil?", options: ["Leaf", "Flower", "Root", "Fruit"], correct: 2 },
        { q: "What is the main organ involved in digestion after the stomach?", options: ["Large intestine", "Small intestine", "Liver", "Pancreas"], correct: 1 },
        { q: "Which galaxy contains our solar system?", options: ["Andromeda Galaxy", "Milky Way Galaxy", "Whirlpool Galaxy", "Sombrero Galaxy"], correct: 1 },
        { q: "What instrument measures temperature?", options: ["Thermometer", "Barometer", "Ammeter", "Seismograph"], correct: 0 },
        { q: "What natural satellite orbits Earth?", options: ["Mars", "Europa", "The Moon", "Titan"], correct: 2 },
        { q: "Which element is essential for making ordinary table salt with chlorine?", options: ["Potassium", "Sodium", "Calcium", "Magnesium"], correct: 1 },
        { q: "What type of animal is a frog?", options: ["Reptile", "Mammal", "Amphibian", "Fish"], correct: 2 },
        { q: "Which planet has a day longer than its year?", options: ["Mercury", "Venus", "Mars", "Uranus"], correct: 1 },
        { q: "What is the largest bone in the human body?", options: ["Tibia", "Femur", "Humerus", "Pelvis"], correct: 1 },
        { q: "Which process turns a solid directly into a gas?", options: ["Condensation", "Sublimation", "Evaporation", "Fusion"], correct: 1 },
        { q: "What kind of scientist studies rocks and Earth materials?", options: ["Biologist", "Geologist", "Physicist", "Meteorologist"], correct: 1 },
        { q: "What is the common name for sodium bicarbonate?", options: ["Table salt", "Baking soda", "Bleach", "Vinegar"], correct: 1 },
        { q: "What part of the ear helps with balance?", options: ["Cochlea", "Eardrum", "Inner ear", "Ear canal"], correct: 2 },
        { q: "Which planet is known as the morning star or evening star?", options: ["Mercury", "Venus", "Saturn", "Neptune"], correct: 1 },
        { q: "What is the study of heredity called?", options: ["Ecology", "Botany", "Genetics", "Zoology"], correct: 2 },
        { q: "Which gas do divers need in tanks for breathing underwater in normal recreational diving?", options: ["Pure nitrogen", "Compressed air", "Helium only", "Carbon monoxide"], correct: 1 },
        { q: "What type of cloud is often associated with thunderstorms?", options: ["Cirrus", "Stratus", "Cumulonimbus", "Altocumulus"], correct: 2 },
        { q: "Which organ stores bile?", options: ["Pancreas", "Gallbladder", "Kidney", "Spleen"], correct: 1 },
        { q: "What is the term for an animal active mainly at night?", options: ["Diurnal", "Nocturnal", "Aquatic", "Migratory"], correct: 1 },
        { q: "Which branch of science deals with chemicals and reactions?", options: ["Physics", "Chemistry", "Astronomy", "Geography"], correct: 1 },
        { q: "What is the center of our solar system?", options: ["Earth", "Jupiter", "The Sun", "The Moon"], correct: 2 },
        { q: "Which gas is often called laughing gas?", options: ["Nitrous oxide", "Carbon monoxide", "Sulfur dioxide", "Methane"], correct: 0 },
        { q: "What type of animal is a whale?", options: ["Fish", "Mammal", "Reptile", "Amphibian"], correct: 1 },
        { q: "Which planet is an ice giant along with Uranus?", options: ["Jupiter", "Saturn", "Neptune", "Mars"], correct: 2 },
        { q: "What is the smallest planet in our solar system as of 2026?", options: ["Mercury", "Mars", "Venus", "Pluto"], correct: 0 },
        { q: "What organ produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Thyroid"], correct: 1 },
        { q: "Which substance do plants primarily use chlorophyll to absorb?", options: ["Sound", "Heat", "Sunlight", "Nitrogen"], correct: 2 },
        { q: "What does a seismograph measure?", options: ["Wind speed", "Rainfall", "Earthquakes", "Air pressure"], correct: 2 },
        { q: "Which vitamin is abundant in citrus fruits?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin E"], correct: 2 },
        { q: "What is the name of the path Earth takes around the Sun?", options: ["Axis", "Orbit", "Rotation", "Equator"], correct: 1 },
        { q: "Which scientist is famous for the equation E = mc^2?", options: ["Isaac Newton", "Galileo", "Albert Einstein", "Niels Bohr"], correct: 2 },
        { q: "Which organ in plants is primarily responsible for photosynthesis?", options: ["Root", "Stem", "Leaf", "Seed"], correct: 2 },
        { q: "What type of energy does a moving object have?", options: ["Potential energy", "Thermal energy", "Kinetic energy", "Chemical energy"], correct: 2 }
    ],
    'Sports & Leisure': [
        { q: "How many players are on a soccer team on the field?", options: ["9", "10", "11", "12"], correct: 2 },
        { q: "In which sport would you perform a slam dunk?", options: ["Volleyball", "Basketball", "Tennis", "Hockey"], correct: 1 },
        { q: "The Olympics are held every how many years?", options: ["2", "3", "4", "5"], correct: 2 },
        { q: "What sport is played at Wimbledon?", options: ["Golf", "Cricket", "Tennis", "Rugby"], correct: 2 },
        { q: "How many holes are there in a standard round of golf?", options: ["9", "12", "15", "18"], correct: 3 },
        { q: "In which country did the modern Olympic Games originate?", options: ["Greece", "Italy", "France", "England"], correct: 0 },
        { q: "What is the national sport of Japan?", options: ["Judo", "Karate", "Sumo", "Kendo"], correct: 2 },
        { q: "How many rings are on the Olympic flag?", options: ["4", "5", "6", "7"], correct: 1 },
        { q: "In bowling, what is three strikes in a row called?", options: ["Hat trick", "Turkey", "Triple", "Threepeat"], correct: 1 },
        { q: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "Italy"], correct: 2 },
        { q: "How many players are on a basketball team on the court?", options: ["4", "5", "6", "7"], correct: 1 },
        { q: "In which sport is the term 'home run' used?", options: ["Cricket", "Baseball", "Rugby", "Hockey"], correct: 1 },
        { q: "What sport uses a shuttlecock?", options: ["Squash", "Tennis", "Badminton", "Table tennis"], correct: 2 },
        { q: "How many points is a touchdown worth in American football?", options: ["3", "5", "6", "7"], correct: 2 },
        { q: "Which sport is associated with the Stanley Cup?", options: ["Basketball", "Ice hockey", "Baseball", "Golf"], correct: 1 },
        { q: "In golf, what is one stroke under par called?", options: ["Bogey", "Birdie", "Eagle", "Ace"], correct: 1 },
        { q: "Which country hosts the Tour de France?", options: ["Italy", "Belgium", "France", "Spain"], correct: 2 },
        { q: "What sport is known as the 'king of sports' in many countries?", options: ["Basketball", "Soccer", "Tennis", "Baseball"], correct: 1 },
        { q: "How many players are on a volleyball team on the court?", options: ["5", "6", "7", "8"], correct: 1 },
        { q: "What is a perfect score in ten-pin bowling?", options: ["200", "250", "300", "350"], correct: 2 },
        { q: "Which sport uses the terms love, deuce, and ace?", options: ["Badminton", "Tennis", "Table tennis", "Volleyball"], correct: 1 },
        { q: "In which sport would you use a pommel horse?", options: ["Equestrian", "Gymnastics", "Wrestling", "Fencing"], correct: 1 },
        { q: "How long is a standard marathon?", options: ["26.2 miles", "20 miles", "24.5 miles", "30 miles"], correct: 0 },
        { q: "Which country invented table tennis?", options: ["China", "England", "Japan", "South Korea"], correct: 1 },
        { q: "What color card means a player is sent off in soccer?", options: ["Blue", "Yellow", "Green", "Red"], correct: 3 },
        { q: "In baseball, how many strikes make an out?", options: ["2", "3", "4", "5"], correct: 1 },
        { q: "Which sport features the apparatus called uneven bars?", options: ["Figure skating", "Gymnastics", "Diving", "Weightlifting"], correct: 1 },
        { q: "What is the maximum score with one dart in standard darts?", options: ["50", "60", "100", "180"], correct: 1 },
        { q: "Which sport is associated with Wimbledon?", options: ["Squash", "Tennis", "Cricket", "Croquet"], correct: 1 },
        { q: "How many players are on an ice hockey team on the ice including the goalie?", options: ["5", "6", "7", "8"], correct: 1 },
        { q: "What is the term for three goals by one player in a game?", options: ["Triple", "Hat trick", "Treble", "Clean sweep"], correct: 1 },
        { q: "Which sport uses a scrum?", options: ["American football", "Rugby", "Lacrosse", "Field hockey"], correct: 1 },
        { q: "In which sport can you score a hole-in-one?", options: ["Mini golf", "Golf", "Croquet", "Polo"], correct: 1 },
        { q: "Which country won the FIFA World Cup in 2018?", options: ["Croatia", "Germany", "France", "Argentina"], correct: 2 },
        { q: "What is the name of the trophy awarded in the NFL championship?", options: ["Heisman Trophy", "Lombardi Trophy", "Stanley Cup", "Commissioner's Trophy"], correct: 1 },
        { q: "Which sport uses a piste?", options: ["Skiing", "Cycling", "Fencing", "Skateboarding"], correct: 2 },
        { q: "How many periods are in a standard ice hockey game?", options: ["2", "3", "4", "5"], correct: 1 },
        { q: "What does NBA stand for?", options: ["National Baseball Association", "National Basketball Association", "Northern Basketball Alliance", "National Boxing Association"], correct: 1 },
        { q: "Which sport uses a balance beam?", options: ["Gymnastics", "Diving", "Skating", "Pole vault"], correct: 0 },
        { q: "How many bases are there on a baseball field?", options: ["3", "4", "5", "6"], correct: 1 },
        { q: "Which sport is the Masters Tournament associated with?", options: ["Tennis", "Golf", "Horse racing", "Snooker"], correct: 1 },
        { q: "In soccer, what body part can the goalkeeper use inside the penalty area?", options: ["Head only", "Feet only", "Hands", "Shoulders only"], correct: 2 },
        { q: "How many players are on a standard rugby union team?", options: ["11", "13", "15", "17"], correct: 2 },
        { q: "What sport features the Tour de France?", options: ["Running", "Motor racing", "Cycling", "Horse racing"], correct: 2 },
        { q: "Which country is strongly associated with sumo wrestling?", options: ["China", "Japan", "Mongolia", "Thailand"], correct: 1 },
        { q: "What is the term for a score of zero in tennis?", options: ["Blank", "Nil", "Love", "Zero"], correct: 2 },
        { q: "Which sport awards the Green Jacket to its winner?", options: ["Cricket", "Golf", "Tennis", "Rugby"], correct: 1 },
        { q: "How many players are on a standard cricket team?", options: ["9", "10", "11", "12"], correct: 2 },
        { q: "Which sport uses clubs, irons, and a putter?", options: ["Croquet", "Baseball", "Golf", "Polo"], correct: 2 },
        { q: "In boxing, how many points is a standard knockdown count usually based on?", options: ["8-count", "10-count", "12-count", "15-count"], correct: 1 },
        { q: "Which sport includes the positions of pitcher and catcher?", options: ["Softball", "Baseball", "Cricket", "Handball"], correct: 1 },
        { q: "Which country won the FIFA Women's World Cup in 2019?", options: ["England", "Netherlands", "United States", "Germany"], correct: 2 },
        { q: "What is the target score in many games of badminton?", options: ["11", "15", "21", "25"], correct: 2 },
        { q: "Which sport has the term 'checkmate'?", options: ["Fencing", "Chess", "Poker", "Snooker"], correct: 1 },
        { q: "In which sport do competitors perform a vault?", options: ["Gymnastics", "Diving", "Figure skating", "Biathlon"], correct: 0 },
        { q: "How many minutes are in a standard soccer match, excluding stoppage time?", options: ["80", "90", "100", "120"], correct: 1 },
        { q: "What sport uses a cue ball?", options: ["Darts", "Snooker", "Bowling", "Curling"], correct: 1 },
        { q: "Which race is known as 'The Greatest Two Minutes in Sports'?", options: ["Indy 500", "Kentucky Derby", "Boston Marathon", "Preakness Stakes"], correct: 1 },
        { q: "In basketball, how many points is a shot from beyond the arc worth?", options: ["2", "3", "4", "5"], correct: 1 },
        { q: "Which sport uses the terms strike and spare?", options: ["Baseball", "Bowling", "Darts", "Cricket"], correct: 1 },
        { q: "How many players are on a standard water polo team in the pool?", options: ["6", "7", "8", "9"], correct: 1 },
        { q: "Which sport has positions called scrum-half and fly-half?", options: ["Soccer", "Rugby", "Cricket", "Handball"], correct: 1 },
        { q: "Which sport uses a pommel horse and rings?", options: ["Gymnastics", "Equestrian", "Wrestling", "Weightlifting"], correct: 0 },
        { q: "What is the term for a tied score in golf match play after all holes are completed?", options: ["All square", "Even par", "Dead heat", "Push"], correct: 0 },
        { q: "Which country is associated with the haka in rugby?", options: ["Australia", "South Africa", "New Zealand", "Fiji"], correct: 2 },
        { q: "What is the highest possible break in snooker?", options: ["147", "155", "180", "200"], correct: 0 },
        { q: "Which sport features the Ashes series?", options: ["Baseball", "Cricket", "Rugby", "Tennis"], correct: 1 },
        { q: "How many players start for one team in baseball on defense?", options: ["8", "9", "10", "11"], correct: 1 },
        { q: "Which sport includes events like slalom and downhill?", options: ["Snowboarding", "Alpine skiing", "Bobsleigh", "Biathlon"], correct: 1 },
        { q: "What does VAR stand for in soccer?", options: ["Video Assistant Referee", "Virtual Action Review", "Verified Athletic Replay", "Video Appeal Rule"], correct: 0 },
        { q: "Which sport is known for the Davis Cup?", options: ["Tennis", "Golf", "Rugby", "Cricket"], correct: 0 },
        { q: "How many lanes are typically used in an Olympic swimming pool for competition?", options: ["6", "8", "10", "12"], correct: 1 },
        { q: "Which sport uses the terms end and house?", options: ["Curling", "Bowls", "Darts", "Croquet"], correct: 0 },
        { q: "What is the name of the championship game of the NFL?", options: ["World Series", "Super Bowl", "Final Four", "Rose Bowl"], correct: 1 },
        { q: "In track and field, how many hurdles are in the men's 110-meter hurdles?", options: ["8", "10", "12", "14"], correct: 1 },
        { q: "Which sport features the position of libero?", options: ["Volleyball", "Basketball", "Handball", "Water polo"], correct: 0 },
        { q: "What is the oldest tennis tournament in the world?", options: ["US Open", "French Open", "Wimbledon", "Australian Open"], correct: 2 },
        { q: "Which sport uses a foil, epee, or sabre?", options: ["Archery", "Fencing", "Kendo", "Lacrosse"], correct: 1 },
        { q: "How many rounds are there in a professional heavyweight boxing title bout?", options: ["10", "12", "15", "18"], correct: 1 },
        { q: "Which country hosts the Indianapolis 500?", options: ["Canada", "United States", "United Kingdom", "Australia"], correct: 1 },
        { q: "What is a bullseye worth on a standard dartboard?", options: ["25 or 50 depending on center ring", "40", "60", "100"], correct: 0 },
        { q: "Which sport includes the terms pommel, vault, and floor exercise?", options: ["Diving", "Gymnastics", "Skateboarding", "Wrestling"], correct: 1 },
        { q: "How many players are on a standard handball team on court?", options: ["6", "7", "8", "9"], correct: 1 },
        { q: "Which country won the men's FIFA World Cup in 2022?", options: ["France", "Brazil", "Argentina", "Croatia"], correct: 2 },
        { q: "What sport is associated with the Ryder Cup?", options: ["Golf", "Cricket", "Tennis", "Rugby"], correct: 0 },
        { q: "Which sport uses a scrum, line-out, and try?", options: ["American football", "Rugby", "Soccer", "Lacrosse"], correct: 1 },
        { q: "How many sets must a player usually win in a women's Grand Slam singles tennis final?", options: ["1", "2", "3", "5"], correct: 1 },
        { q: "Which sport includes pommel horse, still rings, and parallel bars?", options: ["Gymnastics", "Weightlifting", "Fencing", "Diving"], correct: 0 },
        { q: "What color jersey is traditionally worn by the Tour de France overall leader?", options: ["Green", "White", "Yellow", "Red"], correct: 2 },
        { q: "Which sport uses the term 'tee' at the start of play?", options: ["Golf", "Baseball", "Cricket", "Rugby"], correct: 0 },
        { q: "In volleyball, how many touches are allowed before the ball must cross the net?", options: ["2", "3", "4", "5"], correct: 1 },
        { q: "Which sport is measured in overs?", options: ["Baseball", "Cricket", "Rugby", "Polo"], correct: 1 },
        { q: "What is the national governing event known as the Triple Crown commonly associated with in the U.S.?", options: ["Horse racing", "Cycling", "Golf", "Baseball"], correct: 0 },
        { q: "Which sport uses a shuttlecock and a net but no table?", options: ["Tennis", "Badminton", "Volleyball", "Squash"], correct: 1 },
        { q: "How many players are on one side in doubles tennis?", options: ["1", "2", "3", "4"], correct: 1 },
        { q: "Which sport has faceoffs and body checking?", options: ["Field hockey", "Ice hockey", "Lacrosse", "Rugby"], correct: 1 },
        { q: "What is the term for a score of one under par on a hole in golf?", options: ["Bogey", "Birdie", "Eagle", "Albatross"], correct: 1 },
        { q: "Which sport awards a green jersey for points classification in the Tour de France?", options: ["Cycling", "Running", "Skiing", "Triathlon"], correct: 0 },
        { q: "Which sport uses a mat, pins, and takedowns?", options: ["Judo", "Wrestling", "Boxing", "Fencing"], correct: 1 },
        { q: "How many holes are played in a full round of mini-golf typically in many courses?", options: ["9", "12", "18", "27"], correct: 2 },
        { q: "Which sport includes the events of singles, doubles, and mixed doubles at the Olympics?", options: ["Badminton", "Both tennis and badminton", "Table tennis only", "Volleyball"], correct: 1 },
        { q: "What is the term for a no-score tie in baseball before anyone scores?", options: ["Love-all", "Nil-nil", "Scoreless tie", "Deadlock"], correct: 2 },
        { q: "Which sport is associated with the Claret Jug?", options: ["Rugby", "Golf", "Cricket", "Sailing"], correct: 1 },
        { q: "Which country is historically associated with cricket's Lord's ground?", options: ["Australia", "India", "England", "South Africa"], correct: 2 },
        { q: "What sport uses a saddle, reins, and stirrups in competition?", options: ["Cycling", "Equestrian", "Polo only", "Rowing"], correct: 1 }
    ]
};

